### ISSUE TITLE
asn1: structure error while parsing mozilla profile

### ISSUE THREAD

**Issue by egglessness** [rusq/gonss3#2]
I'm trying to decrypt Firefox passwords using the provided example, like this:
```go
p = "C:\Users\REDACTED\AppData\Roaming\Mozilla\Firefox\Profiles\REDACTED.default-esr"
profile, err := gonss3.New(p, []byte(""))
```
but I receive the following error:
```
panic: asn1: structure error: tags don't match (4 vs {class:0 tag:16 length:65 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}  @2
```

I'm currently using Firefox version `91.10.0esr (64-bit)` on Windows 10. 

Any idea on how can I get past this issue?

**Comment by rusq** [comment]
I don't have a firefox currently, will have to install it at some point.

Could you try this tool for now and see if that works? 
https://github.com/rusq/browserpass

It uses gonss3 library for firefox, and as far as I remember, it worked last time I tested it:
https://github.com/rusq/browserpass/blob/master/firefox.go#L85

**Comment by rusq** [comment]
Just to add, if you're using it on windows, you might be better off with CGO implementation that I wrote for that project:
https://github.com/rusq/browserpass/blob/master/firefoxnss_windows.go

It uses Mozilla `nss.dll`, which should provide up to date encrypt/decrypt functions.
